export const getAllChallenge = "SELECT * FROM license_challenge.challenge LIMIT "
export const getCategoryChallenge = "SELECT * FROM license_challenge.challenge WHERE challengeCategory = ? LIMIT "
export const getChallenge = "SELECT * FROM license_challenge.challenge WHERE challengeId = ?;"
export const createChallenge = "INSERT INTO license_challenge.challenge (challengeTitle, challengeCategory, scheduleId, leaderId, proofMethod, proofCount, proofCountOneDay, chgStartDt, chgEndDt, challengeTerm, challengeTitleImage, challengeInroduction, goodProofImage, badProofImage, deposit, limitPeople, joinPeople) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?);"
export const deleteChallenge = "DELETE FROM license_challenge.challenge WHERE challengeId = ?;"