export const getAllChallenge = "SELECT challengeId a, challengeId, challengeTitle, IF(challenge.licenseId IS NULL, NULL, (SELECT license.licenseName FROM challenge,license WHERE challenge.licenseId=license.licenseId AND challenge.challengeId=a)) AS licenseName, proofCount, proofCountOneDay, challengeTitleImage, deposit, challengeCreateDt FROM challenge ORDER BY challengeCreateDt DESC LIMIT "
export const getLicenseChallenges = "SELECT challenge.challengeId, challenge.challengeTitle, license.licenseName, challenge.proofCount, challenge.proofCountOneDay, challenge.challengeTitleImage, challenge.deposit FROM challenge, license WHERE challenge.licenseId=license.licenseId AND challengeCategory = '자격증' ORDER BY challengeCreateDt DESC LIMIT "
export const getOtherChallenges = "SELECT challenge.challengeId, challenge.challengeTitle, NULL as licenseName,  challenge.proofCount, challenge.proofCountOneDay, challenge.challengeTitleImage, challenge.deposit, challengeCreateDt FROM challenge WHERE challenge.licenseId IS NULL AND challengeCategory = ? ORDER BY challengeCreateDt DESC LIMIT "
export const getOneChallenge = "SELECT challenge.*, IF(challenge.licenseId IS NULL, NULL, (SELECT license.licenseName FROM challenge,license WHERE challenge.licenseId=license.licenseId AND challenge.challengeId=?)) AS licenseName, user.nickname AS 'leaderName', user.profileImage AS 'leaderProfileImage' FROM challenge, user WHERE challengeId=? AND challenge.leaderId=user.userId"
export const createLicenseChallenge = "INSERT INTO license_challenge.challenge (challengeTitle, challengeCategory, licenseId, leaderId, proofMethod, proofAvailableDay, proofCount, proofCountOneDay, chgStartDt, chgEndDt, challengeTitleImage, challengeIntroduction, goodProofImage, badProofImage, deposit, limitPeople, joinPeople) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,1);"
export const createOtherChallenge = "INSERT INTO license_challenge.challenge (challengeTitle, challengeCategory, leaderId, proofMethod, proofAvailableDay, proofCount, proofCountOneDay, chgStartDt, chgEndDt, challengeTitleImage, challengeIntroduction, goodProofImage, badProofImage, deposit, limitPeople, joinPeople) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,1);"
export const updateChallenge = "UPDATE challenge SET challengeTitle= ?, proofMethod = ?, proofAvailableDay = ?, proofCount = ?, proofCountOneDay = ?, challengeTitleImage = ?, challengeIntroduction = ?, goodProofImage= ?, badProofImage = ?, limitPeople= ? WHERE challengeId = ?"
export const deleteChallenge = "DELETE FROM license_challenge.challenge WHERE challengeId = ?;"
export const getOngoingChallenge = "SELECT challenge.challengeId, challenge.challengeTitle, IF(challenge.licenseId IS NULL, NULL, (SELECT license.licenseName FROM challenge,license,join_challenge WHERE join_challenge.userId=? AND join_challenge.challengeId = challenge.challengeId AND challenge.licenseId=license.licenseId)) AS licenseName, challenge.proofCount, challenge.proofCountOneDay, challenge.challengeTitleImage, challenge.deposit , challenge.chgStartDt,  challenge.chgEndDt, challenge.challengeCreateDt, IFNULL(ROUND((join_challenge.successCnt/(join_challenge.successCnt+join_challenge.failCnt))*100),0) AS achievement_rate FROM challenge, join_challenge WHERE join_challenge.challengeId = challenge.challengeId AND join_challenge.userId=? AND challenge.chgEndDt >= date(now()) ORDER BY challengeCreateDt DESC"
export const getEndedChallenge = "SELECT challenge.challengeId, challenge.challengeTitle, IF(challenge.licenseId IS NULL, NULL, (SELECT license.licenseName FROM challenge,license,join_challenge WHERE join_challenge.userId=? AND join_challenge.challengeId = challenge.challengeId AND challenge.licenseId=license.licenseId)) AS licenseName, challenge.proofCount, challenge.proofCountOneDay, challenge.challengeTitleImage, challenge.deposit , challenge.chgStartDt,  challenge.chgEndDt, challenge.challengeCreateDt, IFNULL(ROUND((join_challenge.successCnt/(join_challenge.successCnt+join_challenge.failCnt))*100),0) AS achievement_rate FROM challenge, join_challenge WHERE join_challenge.challengeId = challenge.challengeId AND join_challenge.userId=? AND challenge.chgEndDt < date(now()) ORDER BY challengeCreateDt DESC"
export const searchChallenge = "SELECT challenge.challengeId, challenge.challengeTitle, NULL as licenseName,  challenge.challengeIntroduction, challenge.proofCount, challenge.proofCountOneDay, challenge.challengeTitleImage, challenge.deposit , challenge.chgStartDt,  challenge.chgEndDt, challenge.challengeCreateDt FROM challenge WHERE challenge.licenseId IS NULL AND concat(challenge.challengeTitle, challenge.challengeIntroduction) regexp ? UNION SELECT challenge.challengeId, challenge.challengeTitle, license.licenseName, challenge.challengeIntroduction, challenge.proofCount, challenge.proofCountOneDay, challenge.challengeTitleImage, challenge.deposit , challenge.chgStartDt,  challenge.chgEndDt, challenge.challengeCreateDt FROM challenge, license WHERE challenge.licenseId=license.licenseId AND concat(challenge.challengeTitle, license.licenseName, challenge.challengeIntroduction) regexp ? ORDER BY challengeCreateDt DESC LIMIT "
export const getAchievementRate = "SELECT challenge.challengeId, challenge.challengeTitle, join_challenge.successCnt, join_challenge.failCnt, IFNULL(ROUND((join_challenge.successCnt/(join_challenge.successCnt+join_challenge.failCnt))*100),0) AS achievement_rate FROM challenge, join_challenge WHERE join_challenge.challengeId = challenge.challengeId AND join_challenge.userId=? AND challenge.challengeId=?"
export const enterChallenge_leader = "INSERT INTO join_challenge(challengeId, userId, successCnt, failCnt, pass) VALUES (?,?,0,0,0)"
export const enterChallenge_follower = "INSERT INTO join_challenge(challengeId, userId, successCnt, failCnt, pass) VALUES (?,?,0,0,0);" 
export const plusJoinPeople = "UPDATE challenge SET joinPeople = joinPeople+1 WHERE challengeId = ?;"
export const getChallengeEndDt = "SELECT chgEndDt FROM challenge WHERE challengeId=?"
export const checkDepositRefund = "SELECT pass, refund_deposit, achievement_rate, ( CASE WHEN 80 <= achievement_rate THEN 100 WHEN  50 <= achievement_rate AND achievement_rate < 80 THEN achievement_rate WHEN achievement_rate < 50 THEN 0 ELSE -1 END ) AS refund_rate FROM join_challenge, (SELECT IFNULL(ROUND((join_challenge.successCnt/(join_challenge.successCnt+join_challenge.failCnt))*100),0) AS achievement_rate FROM join_challenge WHERE userId = ? AND challengeId = ?) B WHERE userId = ? AND challengeId = ?"
export const successDepositRefund = "UPDATE join_challenge SET refund_deposit = 1 WHERE challengeId = ? AND userId = ?"

export const createProofPicture = "INSERT INTO proof_picture(challengeId, userId, proofImage, dailyReview, reportCnt, proof) VALUES(?, ?, ?, ?, 0, 0)"
export const getProofPicture = "SELECT pictureId, proofImage FROM proof_picture WHERE challengeId = ? ORDER BY proofDt DESC LIMIT "
export const getProofPictureDetail = "SELECT pp.pictureId, pp.proofImage, u.nickname, pp.dailyReview, pp.proofDt, pp.reportCnt FROM proof_picture pp, user u WHERE pp.userId = u.userId AND pp.challengeId = ? AND pp.pictureId = ?"

export const getToday = "SELECT case DAYOFWEEK(CURDATE()) when '1' then '일' when '2' then '월' when '3' then '화' when '4' then '수' when '5' then '목' when '6' then '금' when '7' then '토' end as dayofweek"
export const getProofAvailableDay = "SELECT proofAvailableDay from challenge where challengeId = ?"
export const getProofCntOneDay= "SELECT proofCountOneDay FROM challenge WHERE challengeId = ?"
export const getProofCnt = "SELECT proofCount from challenge where challengeId = ?"
export const getUserDayCnt = "SELECT COUNT(*) AS userDayCnt FROM proof_picture WHERE challengeId = ? AND userId = ? AND date(proofDt) = date(curdate())"
export const getUserWeekCnt = "SELECT COUNT(*) AS userWeekCnt FROM proof_picture WHERE date_format(proofDt,'%Y-%m-%d') BETWEEN (SELECT ADDDATE(CURDATE(), - WEEKDAY(CURDATE()) + 0 )) AND (SELECT ADDDATE(CURDATE(), - WEEKDAY(CURDATE()) + 6 )) AND challengeId = ? AND userId = ?"





/////////////자동환급//////////////
//끝난챌린지 id, 보증금
export const getEndedCLG = "SELECT challengeId, deposit, refund FROM challenge WHERE challenge.chgEndDt < date(now()) AND refund=0"
export const getEndedUsers = "SELECT distinct userId, refund_deposit, IFNULL(ROUND((join_challenge.successCnt/(join_challenge.successCnt+join_challenge.failCnt))*100),0) AS achievement_rate FROM join_challenge WHERE challengeId = ?"
export const successDepositRefund2 = "UPDATE challenge SET refund = 1 WHERE challengeId = ?"